---
- name: include vars
  include_vars:
    file: "../vars/secure.yml"

- include_role:
    name: loadblancer

- name: Create VMSS
  azure_rm_virtualmachine_scaleset:
    resource_group: "{{ resourceGroup }}"
    name: "{{ vmssName }}"
    vm_size: "{{ vmStandardSize }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    ssh_password_enabled: true    
    capacity: 2
    security_group: "{{ vmssName }}"
    virtual_network_name: "{{ vmssName }}"
    subnet_name: "{{ vmssName }}"
    upgrade_policy: Manual
    tier: Standard
    managed_disk_type: Standard_LRS
    os_disk_caching: ReadWrite
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
    load_balancer: "{{ vmssLbName }}"
    data_disks:
      - lun: 0
        disk_size_gb: 20
        managed_disk_type: Standard_LRS
        caching: ReadOnly
      - lun: 1
        disk_size_gb: 30
        managed_disk_type: Standard_LRS
        caching: ReadOnly
    os_type: Linux
    tags:
      env: "{{ type }}"
