---
- hosts: env_dev_staticApp
  remote_user: tw_test_devops_admin 
  roles:
    - role: httpd
      tags: ['dev','static']

- hosts: env_dev_webApp
  remote_user: tw_test_devops_admin
  roles:
    - role: tomcat-server
      tags: ['dev','web']