- name: Copy the Zip file
  copy:
    src: "{{ webapp_source_file_path }}"
    dest: "{{ webapp_destination_file_path }}"
    force: yes
  become: yes
  register: copy_status

- name: Check is unzip is present
  package:
    name: unzip
    state: present
  become: yes

- name: Extract archive
  command: unzip {{ webapp_destination_file_path }} -d {{ webapp_destination_folder }}
  # unarchive:
  #  src: "{{ webapp_destination_file_path }}"
  #  dest: "{{ webapp_destination_folder }}"
  #  remote_src: yes
  become: yes
