---
- name: include vars
  include_vars:
    file: "../vars/secure.yml"

- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ resourceGroup }}"
    location: "{{ location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourceGroup }}"
    name: "{{ vmssName }}"
    address_prefixes: "10.0.0.0/16"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resourceGroup }}"
    allocation_method: Static
    name: "{{ vmssName }}"
    domain_name: "{{ domainName }}"

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resourceGroup }}"
    name: "{{ vmssName }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: tomcat_HTTP
        protocol: Tcp
        destination_port_range: 8080
        access: Allow
        priority: 1002
        direction: Inbound
      - name: tomcat_HTTPS
        protocol: Tcp
        destination_port_range: 8443
        access: Allow
        priority: 1003
        direction: Inbound

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resourceGroup }}"
    name: "{{ vmssName }}"
    address_prefix: "10.0.1.0/24"
    virtual_network: "{{ vmssName }}"
    security_group: "{{ vmssName }}"


- name: Azure login
  command: az login --service-principal -u {{ AZURE_CLIENT_ID }} -p {{ AZURE_SECRET }} --tenant {{ AZURE_TENANT }}

- name: Create Network Load Balancer
  command: az network lb create --resource-group {{ resourceGroup }} --name {{ vmssLbName }} --public-ip-address {{ vmssName }} --frontend-ip-name {{ vmssName }} --backend-pool-name {{ vmssName }} --public-ip-address-allocation Static

- name: Create Load Balancer Probe
  command: az network lb probe create --resource-group {{ resourceGroup }} --lb-name {{ vmssLbName }} --name {{ vmssName }} --protocol tcp --port 8080 --interval 10 --threshold 3

- name: Create Load Balancer Rule
  command: az network lb rule create --resource-group {{ resourceGroup }} --lb-name {{ vmssLbName }} --name {{ vmssName }}_HTTP --protocol tcp --frontend-port 80 --backend-port 8080 --frontend-ip-name {{ vmssName }} --backend-pool-name {{ vmssName }} --probe-name {{ vmssName }} --load-distribution Default --idle-timeout 4

- name: Create Load Balancer Rule 2
  command: az network lb rule create --resource-group {{ resourceGroup }} --lb-name {{ vmssLbName }} --name {{ vmssName }}_HTTPS --protocol tcp --frontend-port 80 --backend-port 8080 --frontend-ip-name {{ vmssName }} --backend-pool-name {{ vmssName }} --probe-name {{ vmssName }} --load-distribution Default --idle-timeout 4
  
- name: Create inbound NAT pool
  command: az network lb inbound-nat-pool create --backend-port 22 --frontend-port-range-end 50040 --frontend-port-range-start 50000 --lb-name {{ vmssLbName }} --name {{ vmssName }} --protocol Tcp --resource-group {{ resourceGroup }} --frontend-ip-name {{ vmssName }}

#- name: Create a load balancer
#  azure_rm_loadbalancer:
#    name: "{{ vmssLbName }}"
#    location: "{{ location }}"
#    resource_group: "{{ resourceGroup }}"
#    backend_address_pools:
#      - name: "{{ vmssName }}"
#    frontend_ip_configurations:
#      - name: "{{ vmssName }}"
#        private_ip_allocation_method: Dynamic
#        public_ip_address: "{{ vmssName }}"
#    probes:
#      - name: "{{ vmssName }}"
#        protocol: Tcp
#        port: 8080
#        interval: 10
#        fail_count: 3
#    load_balancing_rules:
#      - name: "{{ vmssName }}"
#        load_distribution: Default      
#        frontend_ip_configuration: "{{ vmssName }}"
#        probe: "{{ vmssName }}"
#        backend_address_pool : "{{ vmssName }}"
#        frontend_port: 80    
#        idle_timeout: 4
#        backend_port: 8080
#        protocol: Tcp
#      - name: "{{ vmssName }}_2"
#        load_distribution: Default      
#        frontend_ip_configuration: "{{ vmssName }}"
#        probe: "{{ vmssName }}"
#        backend_address_pool : "{{ vmssName }}"
#        frontend_port: 443   
#        idle_timeout: 4
#        backend_port: 8443
#        protocol: Tcp
#    inbound_nat_pools:
#      - name: "{{ vmssName }}"
#        backend_port: 22
#        frontend_port_range_start: 50000
#        frontend_port_range_end : 50040
#        frontend_ip_configuration_name: "{{ vmssName }}"
#        protocol: Tcp