---
- name: include vars
  include_vars:
    file: "../vars/secure.yml"

- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ tf_resourceGroup }}"
    location: global

- name: Create Traffic Manager
  azure_rm_trafficmanager:
    name: "{{ tf_name }}"
    resource_group: "{{ tf_resourceGroup }}"
    location: global
    profile_status: enabled
    routing_method: weighted
    dns_config:
      relative_name: "{{ tf_dns_name }}"
      ttl: 60
    monitor_config:
      protocol: HTTP
      port: 80
      path: '/'
    tags:
      Environment: Dev

- name: create a endpoint for a traffic manager profile
  azure_rm_trafficmanagerendpoint:
      resource_group: "{{ resourceGroup }}"
      profile_name: "{{ tf_profileName }}"
      name: "{{ tf_endPointName }}"
      type: azure_endpoints
      location: "{{ location }}"
      priority: 2
      weight: "{{ tf_weight }}"
      target: "{{ domainName }}.{{ location }}.cloudapp.azure.com"
