---
- name: include vars
  include_vars:
    file: "../vars/secure.yml"

- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ resourceGroup }}"
    location: "{{ location }}"

- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{ resourceGroup }}"
    name: "{{ storageAccountName }}"
    account_type: Standard_LRS

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourceGroup }}"
    name: "{{ virtualNetwork }}"
    address_prefixes: "10.10.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resourceGroup }}"
    name: "{{ subnetName }}"
    address_prefix: "10.10.0.0/24"
    virtual_network: "{{ virtualNetwork }}"
    security_group: "{{ securityGroupName }}"

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ resourceGroup }}"
    allocation_method: Static
    name: "{{ publicIPName }}"

- name: Create security group that allows SSH, Apache HTTP and Apache HTTPS
  azure_rm_securitygroup:
    resource_group: "{{ resourceGroup }}"
    name: "{{ securityGroupName }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: tomcat_HTTP
        protocol: Tcp
        destination_port_range: 8085
        access: Allow
        priority: 102
        direction: Inbound
      - name: tomcat_HTTPS
        protocol: Tcp
        destination_port_range: 8443
        access: Allow
        priority: 103
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 104
        direction: Inbound
      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 105
        direction: Inbound
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ resourceGroup }}"
    name: "{{ networkInferace }}"
    virtual_network: "{{ virtualNetwork }}"
    subnet: "{{ subnetName }}"
    ip_configurations:
      - name: "{{ ipconfigurationName }}"
        public_ip_address_name: "{{ publicIPName }}"
        public_ip_allocation_method: Dynamic
        primary: yes
    security_group: "{{ securityGroupName }}"

- name: Create Virtual Machine
  azure_rm_virtualmachine:
    resource_group: "{{ resourceGroup }}"
    name: "{{ VMName }}"
    vm_size: "{{ vmStandardSize }}"
    storage_account: "{{ storageAccountName }}"
    tags:
      env: "{{ type }}"
    admin_username: "{{ admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys: 
      - path: /home/{{ admin_username }}/.ssh/authorized_keys
        key_data: "{{ ssh_keys }}"
    network_interfaces: "{{ networkInferace }}"
    image:
      offer: UbuntuServer 
      publisher: Canonical
      sku: '18.04-LTS'
      version: latest
